// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vShop.Data.EF;

#nullable disable

namespace vShop.Data.Migrations
{
    [DbContext(typeof(vShopDbContext))]
    [Migration("20221106125645_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("vShop.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsShownOnHome")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd2a2b8d-2531-41d8-9383-2c1ed5277e6b"),
                            Desc = "Các mẫu điện thoại",
                            IsShownOnHome = true,
                            Name = "Điện thoại",
                            SortOrder = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ab516751-779e-4eba-9722-0610dbd94115"),
                            Desc = "Các mẫu tivi",
                            IsShownOnHome = true,
                            Name = "Ti vi",
                            SortOrder = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("47c0d505-234c-4f80-805b-284d6ac2c9b7"),
                            Desc = "Các mẫu tủ lạnh",
                            IsShownOnHome = true,
                            Name = "Tủ lạnh",
                            SortOrder = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("vShop.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("261287a7-aab9-497a-ad90-2d36154c4a15"),
                            CategoryId = new Guid("cd2a2b8d-2531-41d8-9383-2c1ed5277e6b"),
                            Desc = "Được cho ra mắt vào tháng 02/2022, Samsung Galaxy S22 Ultra 5G gây sốt trong cộng đồng công nghệ bởi hiệu năng mạnh mẽ, thiết kế đẳng cấp sang trọng cùng nhiều tiện ích do bút S Pen mang lại.",
                            Image = "https://cdn.tgdd.vn/Products/Images/42/235838/samsung-galaxy-s22-ultra-1-1.jpg",
                            Name = "Điện thoại Samsung Galaxy S22 Ultra 5G 128GB",
                            OriginalPrice = 30990000m,
                            Price = 25990000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dd250e6e-7c28-4eff-91d5-646ecde41a86"),
                            CategoryId = new Guid("cd2a2b8d-2531-41d8-9383-2c1ed5277e6b"),
                            Desc = "Sau chiếc điện thoại iPhone Xr, Apple tiếp tục ra mắt siêu phẩm 2019 mang tên iPhone 11 64GB - một smartphone được nâng cấp toàn diện từ thiết kế cao cấp, vi xử lý hiệu năng mạnh mẽ đến hệ thống camera chất lượng cùng thời lượng pin vượt trội.",
                            Image = "https://cdn.tgdd.vn/Products/Images/42/153856/Slider/vi-vn-iphone-11-tinhnang.jpg",
                            Name = "Điện thoại iPhone 11 64GB",
                            OriginalPrice = 14990000m,
                            Price = 11990000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cb7b527a-8bd9-409b-800e-77a39300fe00"),
                            CategoryId = new Guid("ab516751-779e-4eba-9722-0610dbd94115"),
                            Desc = "Hòa mình vào thế giới giải trí với màn hình không viền 3 cạnh ấn tượng",
                            Image = "https://cdn.tgdd.vn/Products/Images/1942/235791/led-4k-samsung-ua50au8100-1.jpg",
                            Name = "Smart Tivi Samsung 4K Crystal UHD 50 inch UA50AU8100",
                            OriginalPrice = 17400000m,
                            Price = 12150000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d8e6eb96-7417-4608-b9d9-055da2fba317"),
                            CategoryId = new Guid("ab516751-779e-4eba-9722-0610dbd94115"),
                            Desc = "Google Tivi Sony 4K 55 inch KD-55X80K cho chất lượng hình ảnh sắc nét, độ bão hòa cao, hình ảnh mượt mà, hạn chế nhòe hình nhờ công nghệ nâng cấp chuẩn hình ảnh 4K X-Reality PRO. Công nghệ loa bất đối xứng X-Balanced cho chất lượng âm thanh cao dù thiết kế tivi mỏng.",
                            Image = "https://cdn.tgdd.vn/Products/Images/1942/274761/Slider/android-sony-4k-55-inch-kd-55x80k637844183249225344.jpg",
                            Name = "Google Tivi Sony 4K 55 inch KD - 55X80K",
                            OriginalPrice = 19900000m,
                            Price = 18360000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d264f04b-4b8d-42ba-a753-fd522e99ee46"),
                            CategoryId = new Guid("47c0d505-234c-4f80-805b-284d6ac2c9b7"),
                            Desc = "Dù sở hữu thiết ngăn đá trên truyền thống, tủ lạnh Samsung Inverter 319 lít RT32K5932BY/SV vẫn sẽ mang đến cho không gian bếp nhà bạn một làn gió mới nhờ chất liệu cửa tủ mới lạ. Cửa tủ lạnh được làm từ kim loại phủ sơn bóng giả gương sang trọng, giúp làm bật lên không gian bếp của bạn.",
                            Image = "https://cdn.tgdd.vn/Products/Images/1943/226358/Slider/samsung-rt32k5932by-sv-140821-0852180.png",
                            Name = "Tủ lạnh Samsung Inverter 319 lít RT32K5932BY/SV",
                            OriginalPrice = 10820000m,
                            Price = 15090000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("321189e5-72d4-43f7-b672-603a8aeadd3a"),
                            CategoryId = new Guid("47c0d505-234c-4f80-805b-284d6ac2c9b7"),
                            Desc = "Tủ lạnh LG Inverter 649 Lít GR-B257JDS là mẫu tủ lạnh side by side được trang bị động cơ Linear Inverter giúp tiết kiệm điện năng. Tích hợp khả năng làm lạnh đa chiều giúp hơi lạnh lan toả đều đến các ngăn.",
                            Image = "https://cdn.tgdd.vn/Products/Images/1942/274761/Slider/android-sony-4k-55-inch-kd-55x80k637844183249225344.jpg",
                            Name = "Tủ lạnh LG Inverter 649 Lít GR-B257JDS",
                            OriginalPrice = 23490000m,
                            Price = 17990000m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("vShop.Data.Entities.Product", b =>
                {
                    b.HasOne("vShop.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Product_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("vShop.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
